services:
  # The j40_data_pipeline service runs the ETL pipeline to create the score
  # score:
  #   image: j40_data_pipeline
  #   container_name: j40_data_pipeline_1
  #   build: data/data-pipeline
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - ./data/data-pipeline:/data-pipeline
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     ENV_FOR_DYNACONF: development
  #     PYTHONUNBUFFERED: 1
  #     TZ: America/Los_Angeles
  #     PIPELINE_CMD: $PIPELINE_CMD

  # The score_server serves the data-pipeline volume as a URL
  j40_score_server_jo:
    image: j40_score_server_jo
    container_name: j40_score_server_1_jo
    build: data/data-serve/.
    volumes:
      - ./data/data-pipeline/data_pipeline/data/score:/data/data-pipeline/data_pipeline/data/score
      - ./data/data-pipeline/data_pipeline/data-versions:/data/data-pipeline/data-versions
      # - ./data/data-pipeline/data_pipeline/data/tribal:/data/data-pipeline/data_pipeline/data/tribal
    ports:
      - 3007:8080
    environment:
      TZ: America/Los_Angeles

  #The j40_website service runs the web app / map / site
  j40_website_jo:
    image: j40_website_jo
    container_name: j40_website_1_jo
    build: client
    environment:
      # See the client readme for more info on environment variables:
      # https://github.com/usds/justice40-tool/blob/main/client/README.md
      DATA_SOURCE: local
      TZ: America/Los_Angeles
    volumes:
      - ./client/src:/client/src
    ports:
      - 3008:6000
    depends_on:
      - "j40_score_server_jo"

